name: Deploy Test

on:
  push:
    branches:
      - main
env:
  backend_value: 0
  frontend_value: 0

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: jitterbit/get-changed-files@v1
        id: abc
        with:
          format: space-delimited
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Printing
        id: filenames
        run: |
          echo "All:"
          echo "${{ steps.abc.outputs.all }}"
      - name: Looping file name
        id: looping
        run: |
          for changed_file in ${{ steps.abc.outputs.all }}; do
            echo "Do something with this ${changed_file}."
            if [[ $changed_file == *"backend"* && env.backend_value==0]]; then
              echo "It's in backend!"
            fi
            if [[ $changed_file == *"frontend"* ]]; then
              echo "It's frontend!"
            fi
          done
          
