name: Deploy Test

on:
  push:
    branches:
      - main
env:
  backend_value: 0
  frontend_value: 0

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          # Enable listing of files matching each filter.
          # Paths to files will be available in `${FILTER_NAME}_files` output variable.
          # Paths will be formatted as JSON array
          list-files: json

          # In this example all changed files are passed to the following action to do
          # some custom processing.
          filters: |
            changed:
              - 'backend/**'
      - name: Lint Markdown
        run: |
          echo "files: ${{ steps.filter.outputs.changed_files }}"
          
