name: Deploy Test

on:
  push:
    branches:
      - main
env:
  backend_value: 0
  frontend_value: 0

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            src:
              - 'backend/**'
          ref: 'main'
          base: ''
          working-directory: ''

      - if: steps.changes.output.src == 'true'
        run: |
          echo "HAHAHHAHAHA"
          
